"""
BuildWise AI — Regional Price Database
=======================================
Construction material prices organized by Indian state and city.
Prices are in INR as of 2024-25 market averages.

Structure: REGIONAL_PRICES[state][city] → dict of material prices
Falls back to state-level defaults if city not found.
"""

from typing import Dict, Any, Optional

# ══════════════════════════════════════════════════════════════════════════════
# REGIONAL PRICE DATABASE
# ══════════════════════════════════════════════════════════════════════════════

REGIONAL_PRICES: Dict[str, Dict[str, Dict[str, float]]] = {
    "maharashtra": {
        "_default": {
            # Structural
            "concrete_rcc_m3": 6200,
            "steel_tmt_kg": 78,
            # Masonry
            "brick_red_pc": 12,
            "block_aac_pc": 60,
            "cement_bag_50kg": 430,
            "sand_m3": 1500,
            "aggregate_20mm_m3": 1700,
            # Finishing
            "plaster_m2": 300,
            "paint_interior_m2": 135,
            "paint_exterior_m2": 175,
            "tiles_m2": 700,
            "waterproofing_m2": 400,
            # Civil
            "excavation_m3": 220,
            "formwork_m2": 160,
            # Labour
            "manday_mason": 800,
            "manday_unskilled": 600,
            "manday_skilled": 900,
        },
        "mumbai": {
            "concrete_rcc_m3": 7000,
            "steel_tmt_kg": 82,
            "brick_red_pc": 14,
            "block_aac_pc": 65,
            "cement_bag_50kg": 450,
            "sand_m3": 1800,
            "aggregate_20mm_m3": 1900,
            "plaster_m2": 350,
            "paint_interior_m2": 150,
            "paint_exterior_m2": 190,
            "tiles_m2": 800,
            "waterproofing_m2": 450,
            "excavation_m3": 280,
            "formwork_m2": 180,
            "manday_mason": 950,
            "manday_unskilled": 700,
            "manday_skilled": 1100,
        },
        "pune": {
            "concrete_rcc_m3": 6000,
            "steel_tmt_kg": 76,
            "brick_red_pc": 11,
            "block_aac_pc": 58,
            "cement_bag_50kg": 420,
            "sand_m3": 1400,
            "aggregate_20mm_m3": 1600,
            "plaster_m2": 280,
            "paint_interior_m2": 125,
            "paint_exterior_m2": 165,
            "tiles_m2": 650,
            "waterproofing_m2": 380,
            "excavation_m3": 200,
            "formwork_m2": 150,
            "manday_mason": 750,
            "manday_unskilled": 550,
            "manday_skilled": 850,
        },
        "nagpur": {
            "concrete_rcc_m3": 5600,
            "steel_tmt_kg": 74,
            "brick_red_pc": 9,
            "block_aac_pc": 52,
            "cement_bag_50kg": 400,
            "sand_m3": 1200,
            "aggregate_20mm_m3": 1400,
            "plaster_m2": 260,
            "paint_interior_m2": 110,
            "paint_exterior_m2": 150,
            "tiles_m2": 600,
            "waterproofing_m2": 350,
            "excavation_m3": 180,
            "formwork_m2": 140,
            "manday_mason": 650,
            "manday_unskilled": 500,
            "manday_skilled": 750,
        },
    },
    "karnataka": {
        "_default": {
            "concrete_rcc_m3": 5800,
            "steel_tmt_kg": 76,
            "brick_red_pc": 10,
            "block_aac_pc": 55,
            "cement_bag_50kg": 420,
            "sand_m3": 1350,
            "aggregate_20mm_m3": 1550,
            "plaster_m2": 280,
            "paint_interior_m2": 120,
            "paint_exterior_m2": 160,
            "tiles_m2": 650,
            "waterproofing_m2": 380,
            "excavation_m3": 200,
            "formwork_m2": 150,
            "manday_mason": 750,
            "manday_unskilled": 550,
            "manday_skilled": 850,
        },
        "bangalore": {
            "concrete_rcc_m3": 6500,
            "steel_tmt_kg": 80,
            "brick_red_pc": 12,
            "block_aac_pc": 62,
            "cement_bag_50kg": 440,
            "sand_m3": 1600,
            "aggregate_20mm_m3": 1750,
            "plaster_m2": 320,
            "paint_interior_m2": 140,
            "paint_exterior_m2": 180,
            "tiles_m2": 750,
            "waterproofing_m2": 420,
            "excavation_m3": 250,
            "formwork_m2": 170,
            "manday_mason": 900,
            "manday_unskilled": 650,
            "manday_skilled": 1000,
        },
    },
    "delhi": {
        "_default": {
            "concrete_rcc_m3": 5500,
            "steel_tmt_kg": 75,
            "brick_red_pc": 10,
            "block_aac_pc": 55,
            "cement_bag_50kg": 430,
            "sand_m3": 1400,
            "aggregate_20mm_m3": 1600,
            "plaster_m2": 280,
            "paint_interior_m2": 120,
            "paint_exterior_m2": 160,
            "tiles_m2": 650,
            "waterproofing_m2": 380,
            "excavation_m3": 200,
            "formwork_m2": 150,
            "manday_mason": 700,
            "manday_unskilled": 550,
            "manday_skilled": 800,
        },
        "new_delhi": {
            "concrete_rcc_m3": 5800,
            "steel_tmt_kg": 78,
            "brick_red_pc": 11,
            "block_aac_pc": 58,
            "cement_bag_50kg": 440,
            "sand_m3": 1500,
            "aggregate_20mm_m3": 1650,
            "plaster_m2": 300,
            "paint_interior_m2": 130,
            "paint_exterior_m2": 170,
            "tiles_m2": 700,
            "waterproofing_m2": 400,
            "excavation_m3": 220,
            "formwork_m2": 160,
            "manday_mason": 800,
            "manday_unskilled": 600,
            "manday_skilled": 900,
        },
        "gurgaon": {
            "concrete_rcc_m3": 6200,
            "steel_tmt_kg": 80,
            "brick_red_pc": 12,
            "block_aac_pc": 60,
            "cement_bag_50kg": 445,
            "sand_m3": 1550,
            "aggregate_20mm_m3": 1700,
            "plaster_m2": 310,
            "paint_interior_m2": 135,
            "paint_exterior_m2": 175,
            "tiles_m2": 720,
            "waterproofing_m2": 410,
            "excavation_m3": 240,
            "formwork_m2": 165,
            "manday_mason": 850,
            "manday_unskilled": 620,
            "manday_skilled": 950,
        },
    },
    "telangana": {
        "_default": {
            "concrete_rcc_m3": 5600,
            "steel_tmt_kg": 74,
            "brick_red_pc": 9,
            "block_aac_pc": 52,
            "cement_bag_50kg": 400,
            "sand_m3": 1300,
            "aggregate_20mm_m3": 1500,
            "plaster_m2": 260,
            "paint_interior_m2": 110,
            "paint_exterior_m2": 150,
            "tiles_m2": 600,
            "waterproofing_m2": 350,
            "excavation_m3": 190,
            "formwork_m2": 140,
            "manday_mason": 700,
            "manday_unskilled": 500,
            "manday_skilled": 800,
        },
        "hyderabad": {
            "concrete_rcc_m3": 6000,
            "steel_tmt_kg": 77,
            "brick_red_pc": 10,
            "block_aac_pc": 56,
            "cement_bag_50kg": 420,
            "sand_m3": 1400,
            "aggregate_20mm_m3": 1600,
            "plaster_m2": 280,
            "paint_interior_m2": 125,
            "paint_exterior_m2": 165,
            "tiles_m2": 650,
            "waterproofing_m2": 380,
            "excavation_m3": 210,
            "formwork_m2": 155,
            "manday_mason": 780,
            "manday_unskilled": 560,
            "manday_skilled": 880,
        },
    },
    "tamil_nadu": {
        "_default": {
            "concrete_rcc_m3": 5400,
            "steel_tmt_kg": 73,
            "brick_red_pc": 8,
            "block_aac_pc": 50,
            "cement_bag_50kg": 390,
            "sand_m3": 1250,
            "aggregate_20mm_m3": 1450,
            "plaster_m2": 250,
            "paint_interior_m2": 105,
            "paint_exterior_m2": 145,
            "tiles_m2": 580,
            "waterproofing_m2": 340,
            "excavation_m3": 180,
            "formwork_m2": 135,
            "manday_mason": 650,
            "manday_unskilled": 480,
            "manday_skilled": 750,
        },
        "chennai": {
            "concrete_rcc_m3": 5900,
            "steel_tmt_kg": 76,
            "brick_red_pc": 10,
            "block_aac_pc": 55,
            "cement_bag_50kg": 410,
            "sand_m3": 1400,
            "aggregate_20mm_m3": 1550,
            "plaster_m2": 280,
            "paint_interior_m2": 120,
            "paint_exterior_m2": 160,
            "tiles_m2": 640,
            "waterproofing_m2": 370,
            "excavation_m3": 200,
            "formwork_m2": 150,
            "manday_mason": 750,
            "manday_unskilled": 550,
            "manday_skilled": 850,
        },
    },
    "gujarat": {
        "_default": {
            "concrete_rcc_m3": 5300,
            "steel_tmt_kg": 72,
            "brick_red_pc": 8,
            "block_aac_pc": 48,
            "cement_bag_50kg": 385,
            "sand_m3": 1200,
            "aggregate_20mm_m3": 1400,
            "plaster_m2": 240,
            "paint_interior_m2": 100,
            "paint_exterior_m2": 140,
            "tiles_m2": 560,
            "waterproofing_m2": 330,
            "excavation_m3": 170,
            "formwork_m2": 130,
            "manday_mason": 620,
            "manday_unskilled": 460,
            "manday_skilled": 720,
        },
        "ahmedabad": {
            "concrete_rcc_m3": 5600,
            "steel_tmt_kg": 75,
            "brick_red_pc": 9,
            "block_aac_pc": 52,
            "cement_bag_50kg": 400,
            "sand_m3": 1300,
            "aggregate_20mm_m3": 1500,
            "plaster_m2": 260,
            "paint_interior_m2": 115,
            "paint_exterior_m2": 155,
            "tiles_m2": 620,
            "waterproofing_m2": 360,
            "excavation_m3": 190,
            "formwork_m2": 145,
            "manday_mason": 700,
            "manday_unskilled": 520,
            "manday_skilled": 800,
        },
    },
    "rajasthan": {
        "_default": {
            "concrete_rcc_m3": 5200,
            "steel_tmt_kg": 73,
            "brick_red_pc": 7,
            "block_aac_pc": 48,
            "cement_bag_50kg": 380,
            "sand_m3": 1100,
            "aggregate_20mm_m3": 1350,
            "plaster_m2": 230,
            "paint_interior_m2": 95,
            "paint_exterior_m2": 135,
            "tiles_m2": 540,
            "waterproofing_m2": 320,
            "excavation_m3": 160,
            "formwork_m2": 125,
            "manday_mason": 600,
            "manday_unskilled": 450,
            "manday_skilled": 700,
        },
        "jaipur": {
            "concrete_rcc_m3": 5500,
            "steel_tmt_kg": 75,
            "brick_red_pc": 8,
            "block_aac_pc": 50,
            "cement_bag_50kg": 395,
            "sand_m3": 1200,
            "aggregate_20mm_m3": 1400,
            "plaster_m2": 250,
            "paint_interior_m2": 110,
            "paint_exterior_m2": 150,
            "tiles_m2": 600,
            "waterproofing_m2": 350,
            "excavation_m3": 180,
            "formwork_m2": 140,
            "manday_mason": 680,
            "manday_unskilled": 500,
            "manday_skilled": 780,
        },
    },
}

# List of available states and cities for the UI
AVAILABLE_REGIONS: Dict[str, list] = {
    "maharashtra": ["Mumbai", "Pune", "Nagpur"],
    "karnataka": ["Bangalore"],
    "delhi": ["New Delhi", "Gurgaon"],
    "telangana": ["Hyderabad"],
    "tamil_nadu": ["Chennai"],
    "gujarat": ["Ahmedabad"],
    "rajasthan": ["Jaipur"],
}

STATE_LABELS: Dict[str, str] = {
    "maharashtra": "Maharashtra",
    "karnataka": "Karnataka",
    "delhi": "Delhi NCR",
    "telangana": "Telangana",
    "tamil_nadu": "Tamil Nadu",
    "gujarat": "Gujarat",
    "rajasthan": "Rajasthan",
}


def get_regional_rates(state: str, city: Optional[str] = None) -> Dict[str, float]:
    """
    Return material rates for a given state and optional city.
    Falls back to state defaults, then to Delhi CPWD defaults.
    """
    state_key = state.lower().replace(" ", "_")

    if state_key not in REGIONAL_PRICES:
        # Fall back to Delhi defaults
        return dict(REGIONAL_PRICES["delhi"]["_default"])

    state_data = REGIONAL_PRICES[state_key]

    if city:
        city_key = city.lower().replace(" ", "_")
        if city_key in state_data:
            return dict(state_data[city_key])

    return dict(state_data["_default"])
